# Generated by Django 2.0.4 on 2018-04-07 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('round', models.CharField(choices=[('GA', 'Grupo A'), ('GB', 'Grupo B'), ('GC', 'Grupo C'), ('GD', 'Grupo D'), ('GE', 'Grupo E'), ('GF', 'Grupo F'), ('GG', 'Grupo G'), ('GH', 'Grupo H'), ('R16', 'Octavos de Final'), ('R8', 'Cuartos de Final'), ('R4', 'Semifinales'), ('R3', 'Partido por Tercer Lugar'), ('R2', 'Finales'), ('C3', 'Tercer Lugar'), ('C2', 'Subcampeón'), ('C1', 'Campeón')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_A', models.IntegerField(null=True)),
                ('score_B', models.IntegerField(null=True)),
                ('real', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('GA', 'Grupo A'), ('GB', 'Grupo B'), ('GC', 'Grupo C'), ('GD', 'Grupo D'), ('GE', 'Grupo E'), ('GF', 'Grupo F'), ('GG', 'Grupo G'), ('GH', 'Grupo H'), ('R16', 'Octavos de Final'), ('R8', 'Cuartos de Final'), ('R4', 'Semifinales'), ('R3', 'Partido por Tercer Lugar'), ('R2', 'Finales'), ('C3', 'Tercer Lugar'), ('C2', 'Subcampeón'), ('C1', 'Campeón')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('group', models.CharField(choices=[('GA', 'Grupo A'), ('GB', 'Grupo B'), ('GC', 'Grupo C'), ('GD', 'Grupo D'), ('GE', 'Grupo E'), ('GF', 'Grupo F'), ('GG', 'Grupo G'), ('GH', 'Grupo H'), ('R16', 'Octavos de Final'), ('R8', 'Cuartos de Final'), ('R4', 'Semifinales'), ('R3', 'Partido por Tercer Lugar'), ('R2', 'Finales'), ('C3', 'Tercer Lugar'), ('C2', 'Subcampeón'), ('C1', 'Campeón')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qualifiedteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='qualifiedteams',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='team_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_A', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_B', to='api.Team'),
        ),
    ]
