version: '3.2'
services:
  db:
    restart: always
    build: ./db
    image: betworldcup_db
    container_name: betworldcup_db
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  app:
    restart: always
    build: .
    image: betworldcup_app
    container_name: betworldcup_app
    depends_on:
      - db
    env_file: .env
    expose:
      - 8080
  web:
    image: nginx:alpine
    container_name: betworldcup_web
    restart: always
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443