#!/bin/bash

pwd=$1
docker exec -i betworldcup_db mysql --default-character-set=utf8 -uworldcupuser -p${pwd} betworldcup < init.sql
./../utils/generate_inserts.py | docker exec -i betworldcup_db mysql --default-character-set=utf8 -uworldcupuser -p${pwd} betworldcup