#!/bin/bash

pwd=$1
file_sql=$2
docker exec -i betworldcup_db mysql --default-character-set=utf8 -uworldcupuser -p${pwd} betworldcup < $file_sql
./../utils/generate_inserts.py | docker exec -i betworldcup_db mysql --default-character-set=utf8 -uworldcupuser -p${pwd} betworldcup